// Central registry of the nine disaster scenarios. Every hazard is defined
// here once; agents, engine and components reference this single source.

import type { HazardDefinition } from '@/hazards/types';

export const HAZARD_DEFS: HazardDefinition[] = [
  {
    id: 'cyclone',
    name: 'Tropical Cyclone',
    category: 'hydromet',
    icon: '🌀',
    description: 'Cyclone landfall + flood compound event — the flagship demo.',
    seed: 1101,
    severity: 'SEVERE',
    accent: '#22d3ee',
    accentSoft: 'rgba(34, 211, 238, 0.16)',
    affectedZones: ['A', 'B', 'F'],
    areaLabel: 'Coastal Region',
    metrics: [
      { key: 'windKmh', label: 'Wind Speed', unit: 'km/h', decimals: 0 },
      { key: 'rainfallMmHr', label: 'Rainfall', unit: 'mm/hr', decimals: 0 },
      { key: 'riverPct', label: 'River Level', unit: '%', decimals: 0 },
      { key: 'floodDepthM', label: 'Peak Flood Depth', unit: 'm', decimals: 1 },
    ],
    layers: [
      { key: 'weather', label: 'Track & Cone', icon: '🌀' },
      { key: 'flood', label: 'Flood Extent', icon: '🌊' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Ambulances', 'Rescue Boats', 'Shelters', 'Helicopters'],
    requiredAgents: ['weather', 'flood', 'evacuation', 'shelter', 'satellite', 'social', 'call-priority', 'resource', 'decision-support', 'report'],
    durationTicks: 44,
    synopsis: 'Cyclone C-07 makes landfall — 340K people across coastal zones at risk.',
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    category: 'geological',
    icon: '🌎',
    description: 'M6.8 seismic event with intensity rings, structural collapse and SAR ops.',
    seed: 1102,
    severity: 'EXTREME',
    accent: '#f59e0b',
    accentSoft: 'rgba(245, 158, 11, 0.16)',
    affectedZones: ['C', 'D', 'E'],
    areaLabel: 'Urban Core & Hills',
    metrics: [
      { key: 'magnitude', label: 'Magnitude', unit: 'Mw', decimals: 1 },
      { key: 'buildingsDamaged', label: 'Buildings Damaged', decimals: 0 },
      { key: 'criticalSos', label: 'Critical SOS', decimals: 0 },
      { key: 'hospitalsUnderLoad', label: 'Hospitals Under Load', decimals: 0 },
      { key: 'depthKm', label: 'Hypocenter Depth', unit: 'km', decimals: 0 },
      { key: 'aftershocks', label: 'Aftershocks', decimals: 0 },
    ],
    layers: [
      { key: 'hazard', label: 'Epicenter', icon: '🎯' },
      { key: 'hazardZone', label: 'Seismic Intensity', icon: '⚡' },
      { key: 'hazardPoints', label: 'Damaged Buildings', icon: '🏚' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Search & Rescue', 'Ambulances', 'Medical Teams', 'Engineers'],
    requiredAgents: ['seismic', 'structural', 'satellite', 'evacuation', 'call-priority', 'resource', 'decision-support', 'report'],
    durationTicks: 40,
    synopsis: 'M6.8 quake strikes Zone C — structural collapse, blocked roads, SAR underway.',
  },
  {
    id: 'volcano',
    name: 'Volcanic Eruption',
    category: 'geological',
    icon: '🌋',
    description: 'Ash plume, lava flow risk and staged evacuation of the hills.',
    seed: 1103,
    severity: 'SIGNIFICANT',
    accent: '#f97316',
    accentSoft: 'rgba(249, 115, 22, 0.16)',
    affectedZones: ['E', 'F'],
    areaLabel: 'Residential Hills & Port',
    metrics: [
      { key: 'vei', label: 'VEI', decimals: 0 },
      { key: 'ashDensity', label: 'Ash Density', unit: 'g/m³', decimals: 1 },
      { key: 'evacZonePct', label: 'Evacuation Zone', unit: '%', decimals: 0 },
      { key: 'airQuality', label: 'Air Quality Index', decimals: 0 },
      { key: 'lavaKm', label: 'Lava Flow', unit: 'km', decimals: 1 },
    ],
    layers: [
      { key: 'hazard', label: 'Volcano & Plume', icon: '🌋' },
      { key: 'hazardZone', label: 'Lava Flow', icon: '🔥' },
      { key: 'hazardPath', label: 'Ash Drift', icon: '💨' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Evacuation Buses', 'Shelters', 'Fire Trucks', 'Drones'],
    requiredAgents: ['seismic', 'satellite', 'evacuation', 'resource', 'decision-support', 'report'],
    durationTicks: 40,
    synopsis: 'Ridge vent erupting — ash drifting toward Zone E, evacuation zone expanding.',
  },
  {
    id: 'tsunami',
    name: 'Tsunami',
    category: 'geological',
    icon: '🌊',
    description: 'Undersea quake, wave propagation rings, coastal inundation.',
    seed: 1104,
    severity: 'EXTREME',
    accent: '#38bdf8',
    accentSoft: 'rgba(56, 189, 248, 0.16)',
    affectedZones: ['A', 'F'],
    areaLabel: 'Coast & Port',
    metrics: [
      { key: 'waveHeightM', label: 'Wave Height', unit: 'm', decimals: 1 },
      { key: 'etaMin', label: 'ETA To Coast', unit: 'min', decimals: 0 },
      { key: 'populationAtRisk', label: 'Coast Pop. At Risk', decimals: 0 },
      { key: 'inundationKm2', label: 'Inundation Area', unit: 'km²', decimals: 1 },
      { key: 'evacProgressPct', label: 'Evacuation Progress', unit: '%', decimals: 0 },
    ],
    layers: [
      { key: 'hazard', label: 'Epicenter', icon: '🎯' },
      { key: 'hazardPath', label: 'Wave Propagation', icon: '〰️' },
      { key: 'hazardZone', label: 'Inundation', icon: '🌊' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Rescue Boats', 'Evacuation Buses', 'Shelters', 'Helicopters'],
    requiredAgents: ['marine', 'seismic', 'evacuation', 'call-priority', 'resource', 'decision-support', 'report'],
    durationTicks: 40,
    synopsis: 'M8.1 undersea earthquake — tsunami wave 4.8 m, ETA 22 min to Zone A coast.',
  },
  {
  id: 'flood',
  name: 'Flood',
  category: 'hydromet',
  icon: '🌧',
  description: 'Standalone catchment flood: rain, river rise, inundation and rescue.',
  seed: 1105,
    severity: 'SEVERE',
    accent: '#3b82f6',
    accentSoft: 'rgba(59, 130, 246, 0.16)',
    affectedZones: ['A', 'B', 'C'],
    areaLabel: 'River Delta',
    metrics: [
      { key: 'rainfallMmHr', label: 'Rainfall', unit: 'mm/hr', decimals: 0 },
      { key: 'riverPct', label: 'River Level', unit: '%', decimals: 0 },
      { key: 'floodDepthM', label: 'Peak Depth', unit: 'm', decimals: 1 },
      { key: 'floodedRoadsKm', label: 'Roads Flooded', unit: 'km', decimals: 1 },
      { key: 'peopleInShelters', label: 'In Shelters', decimals: 0 },
    ],
    layers: [
      { key: 'flood', label: 'Flood Extent', icon: '🌊' },
      { key: 'blockedRoads', label: 'Blocked Roads', icon: '🚧' },
      { key: 'routes', label: 'Detours', icon: '🧭' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Rescue Boats', 'Ambulances', 'Shelters', 'Helicopters'],
    requiredAgents: ['flood', 'weather', 'evacuation', 'social', 'call-priority', 'resource', 'decision-support', 'report'],
    durationTicks: 40,
    synopsis: 'Flash flood on river Ootha — Zone A & B underwater, boats en route.',
  },
  {
  id: 'drought',
  name: 'Drought',
  category: 'climatological',
  icon: '☀️',
  description: 'A slow-burn weeks-long water crisis across the district.',
  seed: 1106,
  severity: 'SEVERE',
    accent: '#d97706',
    accentSoft: 'rgba(217, 119, 6, 0.16)',
    affectedZones: ['A', 'B', 'D'],
    areaLabel: 'Hinterland',
    metrics: [
      { key: 'rainfallDeficit', label: 'Rainfall Deficit', unit: '%', decimals: 0 },
      { key: 'reservoirLevel', label: 'Reservoir Level', unit: '%', decimals: 0 },
      { key: 'groundwaterM', label: 'Groundwater Depth', unit: 'm', decimals: 1 },
      { key: 'waterDemand', label: 'Water Demand', unit: 'ML/day', decimals: 0 },
      { key: 'agriStress', label: 'Agricultural Stress', unit: '%', decimals: 0 },
      { key: 'populationAtRisk', label: 'Population At Risk', decimals: 0 },
    ],
    layers: [
      { key: 'hazardHeat', label: 'Water Stress', icon: '📉' },
      { key: 'hazardPoints', label: 'Affected Wells', icon: '🚰' },
    ],
    timeScale: 'weeks',
    preferredResources: ['Water Tankers', 'Distribution Units', 'Medical Teams'],
    requiredAgents: ['drought', 'resource', 'evacuation', 'decision-support', 'report'],
    durationTicks: 40,
    synopsis: '16-week shortfall — reservoir at 34%, rationing approved for Zone A & B.',
  },
  {
  id: 'tornado',
  name: 'Tornado',
  category: 'hydromet',
  icon: '🌪️',
  description: 'Supercell — EF3 tornado rips across the urban core.',
  seed: 1107,
    accent: '#94a3b4',
    accentSoft: 'rgba(148, 163, 184, 0.16)',
    affectedZones: ['D', 'C', 'B'],
    areaLabel: 'Industrial Belt → Core',
    metrics: [
      { key: 'windKmh', label: 'Wind Speed', unit: 'km/h', decimals: 0 },
      { key: 'widthM', label: 'Tornado Width', unit: 'm', decimals: 0 },
      { key: 'pathKm', label: 'Path Length', unit: 'km', decimals: 1 },
      { key: 'buildingsDamaged', label: 'Buildings Damaged', decimals: 0 },
      { key: 'populationAffected', label: 'Population Affected', decimals: 0 },
    ],
    layers: [
      { key: 'hazardPath', label: 'Tornado Path', icon: '🌪️' },
      { key: 'hazardZone', label: 'Damage Zone', icon: '💥' },
      { key: 'hazard', label: 'Active Cell', icon: '🎯' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Ambulances', 'Search & Rescue', 'Medical Teams'],
    requiredAgents: ['tornado', 'structural', 'satellite', 'call-priority', 'resource', 'decision-support', 'report'],
    durationTicks: 32,
    severity: 'SEVERE',
    synopsis: 'EF3 wedge on the ground — Zone D damage reported, shelter-in-place active.',
  },
  {
  id: 'wildfire',
  name: 'Wildfire',
  category: 'climatological',
  icon: '🔥',
  description: 'Wind-driven fire perimeter expanding across the eastern forest edge.',
  seed: 1108,
  severity: 'SEVERE',
    accent: '#ef4444',
    accentSoft: 'rgba(239, 68, 68, 0.16)',
    affectedZones: ['E', 'F', 'C'],
    areaLabel: 'Hills & Eastern Flank',
    metrics: [
      { key: 'fireAreaKm2', label: 'Fire Area', unit: 'km²', decimals: 1 },
      { key: 'spreadRate', label: 'Spread Rate', unit: 'km²/hr', decimals: 1 },
      { key: 'windKmh', label: 'Wind Speed', unit: 'km/h', decimals: 0 },
      { key: 'smokeAqi', label: 'Smoke AQI', decimals: 0 },
      { key: 'buildingsThreatened', label: 'Buildings Threatened', decimals: 0 },
      { key: 'fireUnits', label: 'Fire Units Active', decimals: 0 },
    ],
    layers: [
      { key: 'hazardZone', label: 'Fire Perimeter', icon: '🔥' },
      { key: 'hazardPath', label: 'Smoke Plume', icon: '💨' },
      { key: 'hazardPoints', label: 'Hotspots', icon: '🟠' },
    ],
    timeScale: 'minutes',
    preferredResources: ['Fire Trucks', 'Helicopters', 'Evacuation Buses'],
    requiredAgents: ['fire', 'satellite', 'evacuation', 'call-priority', 'resource', 'decision-support', 'report'],
    durationTicks: 40,
    synopsis: 'Wind-driven fire — Zone E foothills, perimeter expanding 1.8 km²/hr.',
  },
  {
  id: 'heatwave',
  name: 'Extreme Heat Wave',
  category: 'climatological',
  icon: '🌡️',
  description: 'City-wide heat index surge; cooling centers and water stations open.',
  seed: 1109,
    accent: '#fb923c',
    accentSoft: 'rgba(251, 146, 60, 0.16)',
    affectedZones: ['A', 'C', 'D'],
    areaLabel: 'Urban Core',
    metrics: [
      { key: 'temperatureC', label: 'Temperature', unit: '°C', decimals: 1 },
      { key: 'heatIndex', label: 'Heat Index', unit: '°C', decimals: 1 },
      { key: 'aqi', label: 'AQI', decimals: 0 },
      { key: 'powerDemand', label: 'Power Demand', unit: 'MW', decimals: 0 },
      { key: 'heatCasualties', label: 'Heat-Related SOS', decimals: 0 },
      { key: 'hospitalLoad', label: 'Hospital Load', unit: '%', decimals: 0 },
    ],
    layers: [
      { key: 'hazardHeat', label: 'Temperature Heatmap', icon: '🌡️' },
      { key: 'hazardPoints', label: 'Heat Vulnerability', icon: '💛' },
    ],
    timeScale: 'days',
    preferredResources: ['Water Tankers', 'Cooling Centers', 'Medical Teams'],
    requiredAgents: ['heat', 'resource', 'evacuation', 'call-priority', 'decision-support', 'report'],
    durationTicks: 40,
    severity: 'EXTREME',
    synopsis: '46.2°C heat index 51°C — cooling centers at 3 sites, water stations deployed.',
  },
];

export function hazardDefOf(id: string): HazardDefinition {
  return HAZARD_DEFS.find((h) => h.id === id) ?? HAZARD_DEFS[0];
}

export const HAZARD_DEF_MAP: Record<string, HazardDefinition> = Object.fromEntries(
  HAZARD_DEFS.map((h) => [h.id, h])
);

export const GEO_CATEGORIES: { id: string; label: string; icon: string }[] = [
  { id: 'geological', label: 'GEOLOGICAL', icon: '🌎' },
  { id: 'hydromet', label: 'HYDROLOGICAL & METEOROLOGICAL', icon: '🌧' },
  { id: 'climatological', label: 'CLIMATOLOGICAL', icon: '🔥' },
];